from .batch_image_blend import NODE_CLASS_MAPPINGS as BLEND_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BLEND_DISPLAY_NAMES
from .batch_image_overlay import NODE_CLASS_MAPPINGS as OVERLAY_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OVERLAY_DISPLAY_NAMES

# Merge both node mappings into one
NODE_CLASS_MAPPINGS = {**BLEND_CLASS_MAPPINGS, **OVERLAY_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BLEND_DISPLAY_NAMES, **OVERLAY_DISPLAY_NAMES}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
