from .batch_image_blend import NODE_CLASS_MAPPINGS as BLEND_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BLEND_DISPLAY_NAMES
from .batch_image_overlay import NODE_CLASS_MAPPINGS as OVERLAY_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OVERLAY_DISPLAY_NAMES
from .remove_black_to_transparent import NODE_CLASS_MAPPINGS as REMOVE_BLACK_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as REMOVE_BLACK_DISPLAY_NAMES
from .batch_enlarged_overlay import NODE_CLASS_MAPPINGS as ENLARGED_OVERLAY_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ENLARGED_OVERLAY_DISPLAY_NAMES
from .canny_shrink_recenter import NODE_CLASS_MAPPINGS as CANNY_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CANNY_DISPLAY_NAMES

# Merge all node mappings into one
NODE_CLASS_MAPPINGS = {
    **BLEND_CLASS_MAPPINGS,
    **OVERLAY_CLASS_MAPPINGS,
    **REMOVE_BLACK_CLASS_MAPPINGS,
    **ENLARGED_OVERLAY_CLASS_MAPPINGS,
    **CANNY_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **BLEND_DISPLAY_NAMES,
    **OVERLAY_DISPLAY_NAMES,
    **REMOVE_BLACK_DISPLAY_NAMES,
    **ENLARGED_OVERLAY_DISPLAY_NAMES,
    **CANNY_DISPLAY_NAMES
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

